import "../../src/Behaviour/AnimatedTexture";
import "../../src/Behaviour/BasicControl";
import "../../src/Behaviour/Lara";
import "../../src/Behaviour/MakeLayeredMesh";
import "../../src/Behaviour/RemoveObject";
import "../../src/Behaviour/ScrollTexture";
import "../../src/Behaviour/SetAnimation";
import "../../src/Behaviour/Sprite";
import "../../src/Behaviour/UVRotate";
